### ISSUE TITLE
Hosted package installation does not execute cleanly

### ISSUE THREAD

**Issue by MJJoyce** [NASA-PDS/pds-github-util#25]
## 🐛 Describe the bug
Installation of hosted package fails due to inability to read `requirements.txt` in `tar.gz` distro.

```
(test-py-dep-mgmt) > $ pip install pds-github-util
Collecting pds-github-util
  Downloading pds_github_util-0.23.2.tar.gz (40 kB)
     |████████████████████████████████| 40 kB 1.1 MB/s
    ERROR: Command errored out with exit status 1:
     command: /usr/local/Caskroom/miniconda/base/envs/test-py-dep-mgmt/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/fq/z23zw0pd18x29jndfz5tqwqntzw8gz/T/pip-install-fi_3e2a1/pds-github-util_09b22f6b51b447e6a1b23dbcfa7ffc54/setup.py'"'"'; __file__='"'"'/private/var/folders/fq/z23zw0pd18x29jndfz5tqwqntzw8gz/T/pip-install-fi_3e2a1/pds-github-util_09b22f6b51b447e6a1b23dbcfa7ffc54/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/fq/z23zw0pd18x29jndfz5tqwqntzw8gz/T/pip-pip-egg-info-debtz7wr
         cwd: /private/var/folders/fq/z23zw0pd18x29jndfz5tqwqntzw8gz/T/pip-install-fi_3e2a1/pds-github-util_09b22f6b51b447e6a1b23dbcfa7ffc54/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/fq/z23zw0pd18x29jndfz5tqwqntzw8gz/T/pip-install-fi_3e2a1/pds-github-util_09b22f6b51b447e6a1b23dbcfa7ffc54/setup.py", line 11, in <module>
        with open('requirements.txt', 'r') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/e8/2d/39fb166d8c50ca8305f57f4730fa18225817ae98f7e333721ff95c93bfb9/pds_github_util-0.23.2.tar.gz#sha256=db34443b037d3d8e2465b8f77a9fb382b12c3b678504ffa657276a1ad0b0b5fd (from https://pypi.org/simple/pds-github-util/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading pds_github_util-0.23.0.tar.gz (40 kB)
     |████████████████████████████████| 40 kB 433 kB/s
    ERROR: Command errored out with exit status 1:
     command: /usr/local/Caskroom/miniconda/base/envs/test-py-dep-mgmt/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/fq/z23zw0pd18x29jndfz5tqwqntzw8gz/T/pip-install-fi_3e2a1/pds-github-util_887bfc6ed40941a7861c50dd7bf06670/setup.py'"'"'; __file__='"'"'/private/var/folders/fq/z23zw0pd18x29jndfz5tqwqntzw8gz/T/pip-install-fi_3e2a1/pds-github-util_887bfc6ed40941a7861c50dd7bf06670/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/fq/z23zw0pd18x29jndfz5tqwqntzw8gz/T/pip-pip-egg-info-hrou4di5
         cwd: /private/var/folders/fq/z23zw0pd18x29jndfz5tqwqntzw8gz/T/pip-install-fi_3e2a1/pds-github-util_887bfc6ed40941a7861c50dd7bf06670/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/fq/z23zw0pd18x29jndfz5tqwqntzw8gz/T/pip-install-fi_3e2a1/pds-github-util_887bfc6ed40941a7861c50dd7bf06670/setup.py", line 11, in <module>
        with open('requirements.txt', 'r') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/09/c7/375989d21b66c024f4f4737a36865f62ec9ee060f86a5b891cbd553bd3fe/pds_github_util-0.23.0.tar.gz#sha256=0db80fccb2851060714f1815f2a7c59f1247b0ebcabb717f6579ba11d29ceb14 (from https://pypi.org/simple/pds-github-util/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading pds_github_util-0.22.2-py3-none-any.whl (107 kB)
     |████████████████████████████████| 107 kB 413 kB/s

<snipped remainder of install output>
```

This error seems to be what is plaguing our `github-actions-base` builds (I think). See here:
https://github.com/NASA-PDS/github-actions-base/runs/3487775844?check_suite_focus=true

**NOTE:** The local install doesn't completely fail here because pip ends up pulling `pds_github_util-0.22.2-py3-none-any.whl` and properly installing everything. The GitHub Actions builds don't seem to be so lucky.

## 📜 To Reproduce
1. Create a clean virtual environment
2. Run `pip install pds-github-util`
3. Witness issue

## 🕵️ Expected behavior
An error-free install

## 📚 Version of Software Used
Install is pulling `pds-github-util@0.23.0`

**Comment by MJJoyce** [comment]
Things to think about:
- Don't try to read `requirements.txt` into `setup.py` for pulling dependencies. This is more inline with what our current [template Python repo](https://github.com/NASA-PDS/pds-template-repo-python/) does.
- Should our roundup be updated to only push wheels to PyPI?
- Some combination of both or neither?

@nutjob4life, do you have thoughts here?

**Comment by nutjob4life** [comment]
@MJJoyce wheels all the way. I was hesitant about them in the past but I think they're the right way to go.

Also, I knew setting `install_requires` against `requirements.txt` wasn't right for some reason. You found out why!

**Comment by MJJoyce** [comment]
Ok, perfect. I'll update this so the `requirements.txt` content is stored in `setup.py`. After that a new release should (I hope) fix our other build issues.

Then we can update the roundup at our leisure
